export interface ihomeData{
    title?:string
    name:string
    phon:string
    img?:string
    text1?:string
    text2?:string
    text3?:string
    text4?:string
    text5?:string
    text6?:string
    text7?:string
    text8?:string
    text9?:string
    text10?:string
    text11?:string
    text12?:string
    text13?:string
    text14?:string
    text15?:string
    text16?:string
}